-- 1. Create table if it doesn't exist
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  day_id int not null unique,
  title text not null,
  description text not null,
  icon text not null,
  duration text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Add duration column if it was missing (for safety)
do $$
begin
    if not exists (select 1 from information_schema.columns where table_name = 'tasks' and column_name = 'duration') then
        alter table public.tasks add column duration text;
    end if;
end $$;

-- 3. Enable RLS (if not already enabled)
alter table public.tasks enable row level security;

-- 4. Create Policies (drop existing to avoid errors, then recreate)
drop policy if exists "Tasks are viewable by everyone." on tasks;
create policy "Tasks are viewable by everyone." on tasks for select using ( true );

drop policy if exists "Admins can update tasks." on tasks;
create policy "Admins can update tasks." on tasks for update using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

drop policy if exists "Admins can insert tasks." on tasks;
create policy "Admins can insert tasks." on tasks for insert with check ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

-- 5. Insert Seed Data (Upsert)
insert into public.tasks (day_id, title, description, icon, duration) values
(1, 'Detox de Dopamina', 'Hoje vamos reequilibrar seu sistema de recompensa. Reduza o ruído digital para reencontrar seu foco e clareza mental.', 'Zap', '15 min'),
(2, 'Limpeza Digital', 'Organize seus arquivos e e-mails. Apague aplicativos que você não usa mais e limpe sua caixa de entrada.', 'Trash2', '30 min'),
(3, 'Conexão Real', 'Ligue para um amigo em vez de mandar mensagem. Marque um café ou apenas converse por voz.', 'Phone', '20 min'),
(4, 'Natureza', 'Passe 30 minutos ao ar livre sem celular. Vá a um parque, caminhe na rua ou apenas sente-se no quintal.', 'Leaf', '30 min'),
(5, 'Leitura', 'Leia um capítulo de um livro físico. Nada de Kindle ou ler no celular. Sinta o papel.', 'BookOpen', '1 hora'),
(6, 'Criatividade', 'Desenhe, escreva ou crie algo offline. Use papel e caneta, pinte ou faça um artesanato.', 'PenTool', '45 min'),
(7, 'Reflexão', 'Escreva sobre sua semana de detox. Como você se sentiu? O que mudou na sua rotina?', 'Feather', '15 min')
on conflict (day_id) do update 
set 
  title = excluded.title,
  description = excluded.description,
  icon = excluded.icon,
  duration = excluded.duration;
