-- Create profiles table
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  is_admin boolean default false
);

-- Create tasks table (Content Management)
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  day_id int not null unique,
  title text not null,
  description text not null,
  icon text not null, -- Store lucide icon name
  duration text, -- e.g., "15 min", "1 hora"
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create user_progress table (Updated for detailed check-ins)
create table if not exists public.user_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  day_id int not null,
  status text check (status in ('locked', 'unlocked', 'completed')) default 'locked',
  reflection_text text,
  data jsonb, -- Stores flexible step data (diagnosis, checklist, etc)
  energy_level int, -- 0-10
  focus_level int, -- 0-10
  anxiety_level int, -- 0-10
  sleep_quality int, -- 0-10
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, day_id)
);

-- Create assessments table (Onboarding & Final)
create table if not exists public.assessments (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  type text check (type in ('initial', 'final')) not null,
  usage_time text, -- e.g. "4-6 hours"
  pickup_count text, -- e.g. "50+"
  fatigue_level int, -- 0-10
  focus_level int, -- 0-10
  sleep_quality int, -- 0-10
  anxiety_level int, -- 0-10
  self_esteem_impact int, -- 0-10
  apps text[], -- Array of app names
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create focus_sessions table
create table if not exists public.focus_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  task_name text,
  duration_minutes int not null,
  focus_rating int, -- 0-10
  distractions text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create cravings_log table
create table if not exists public.cravings_log (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  context text, -- where/when
  emotion text,
  app_target text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create sos_logs table
create table if not exists public.sos_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  intensity_before int, -- 0-10
  intensity_after int, -- 0-10
  feeling_after text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.tasks enable row level security;
alter table public.user_progress enable row level security;
alter table public.assessments enable row level security;
alter table public.focus_sessions enable row level security;
alter table public.cravings_log enable row level security;
alter table public.sos_logs enable row level security;

-- Policies

-- Profiles
drop policy if exists "Public profiles are viewable by everyone." on profiles;
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );

drop policy if exists "Users can insert their own profile." on profiles;
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );

drop policy if exists "Users can update own profile." on profiles;
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

-- Tasks
drop policy if exists "Tasks are viewable by everyone." on tasks;
create policy "Tasks are viewable by everyone." on tasks for select using ( true );

drop policy if exists "Admins can update tasks." on tasks;
create policy "Admins can update tasks." on tasks for update using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

drop policy if exists "Admins can insert tasks." on tasks;
create policy "Admins can insert tasks." on tasks for insert with check ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

-- User Progress
drop policy if exists "Users can view own progress." on user_progress;
create policy "Users can view own progress." on user_progress for select using ( auth.uid() = user_id );

drop policy if exists "Users can insert own progress." on user_progress;
create policy "Users can insert own progress." on user_progress for insert with check ( auth.uid() = user_id );

drop policy if exists "Users can update own progress." on user_progress;
create policy "Users can update own progress." on user_progress for update using ( auth.uid() = user_id );

-- Assessments
drop policy if exists "Users can view own assessments." on assessments;
create policy "Users can view own assessments." on assessments for select using ( auth.uid() = user_id );

drop policy if exists "Users can insert own assessments." on assessments;
create policy "Users can insert own assessments." on assessments for insert with check ( auth.uid() = user_id );

-- Focus Sessions
drop policy if exists "Users can view own focus sessions." on focus_sessions;
create policy "Users can view own focus sessions." on focus_sessions for select using ( auth.uid() = user_id );

drop policy if exists "Users can insert own focus sessions." on focus_sessions;
create policy "Users can insert own focus sessions." on focus_sessions for insert with check ( auth.uid() = user_id );

-- Cravings Log
drop policy if exists "Users can view own cravings." on cravings_log;
create policy "Users can view own cravings." on cravings_log for select using ( auth.uid() = user_id );

drop policy if exists "Users can insert own cravings." on cravings_log;
create policy "Users can insert own cravings." on cravings_log for insert with check ( auth.uid() = user_id );

-- SOS Logs
drop policy if exists "Users can view own sos logs." on sos_logs;
create policy "Users can view own sos logs." on sos_logs for select using ( auth.uid() = user_id );

drop policy if exists "Users can insert own sos logs." on sos_logs;
create policy "Users can insert own sos logs." on sos_logs for insert with check ( auth.uid() = user_id );

-- Seed Data for Tasks (Initial 7 Days)
insert into public.tasks (day_id, title, description, icon, duration) values
(1, 'Detox de Dopamina', 'Reduza o uso de redes sociais por 24h.', 'Zap', '15 min'),
(2, 'Limpeza Digital', 'Organize seus arquivos e e-mails.', 'Trash2', '30 min'),
(3, 'Conexão Real', 'Ligue para um amigo em vez de mandar mensagem.', 'Phone', '20 min'),
(4, 'Natureza', 'Passe 30 minutos ao ar livre sem celular.', 'Leaf', '30 min'),
(5, 'Leitura', 'Leia um capítulo de um livro físico.', 'BookOpen', '1 hora'),
(6, 'Criatividade', 'Desenhe, escreva ou crie algo offline.', 'PenTool', '45 min'),
(7, 'Reflexão', 'Escreva sobre sua semana de detox.', 'Feather', '15 min')
on conflict (day_id) do nothing;

-- TRIGGER: Create Profile on Signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger definition
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
